// <auto-generated />
using System;
using DBSenorialModels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBSenorialModels.Data.Migraciones
{
    [DbContext(typeof(DBSenorialContext))]
    partial class DBSenorialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBSenorialModels.Senorial.Ambiente", b =>
                {
                    b.Property<int>("IdAmbiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ambiente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAmbiente"));

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAmbiente")
                        .HasName("ambiente_id_pk");

                    b.HasIndex("IdMesa");

                    b.ToTable("ambiente", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.AperturaCaja", b =>
                {
                    b.Property<int>("IdApertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_apertura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApertura"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<decimal?>("Faltante")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("faltante");

                    b.Property<DateTime>("HoraFechaCierre")
                        .HasColumnType("datetime")
                        .HasColumnName("hora_fecha_cierre");

                    b.Property<DateTime>("HoraFechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("hora_fecha_inicio");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int")
                        .HasColumnName("id_caja");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("MontoCierre")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_cierre");

                    b.Property<decimal>("MontoInicio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_inicio");

                    b.Property<decimal?>("Sobrante")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("sobrante");

                    b.HasKey("IdApertura")
                        .HasName("apertura_caja_id_pk");

                    b.HasIndex("IdCaja");

                    b.ToTable("apertura_cajas", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_caja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaja"));

                    b.Property<string>("NumeroCaja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("numero_caja");

                    b.HasKey("IdCaja")
                        .HasName("caja_id_pk");

                    b.ToTable("cajas", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<int?>("IdCategoriaPadre")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_padre");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria")
                        .HasName("categoria_id_pk");

                    b.HasIndex("IdCategoriaPadre");

                    b.HasIndex(new[] { "Nombre" }, "categorias_nombre_uk")
                        .IsUnique();

                    b.ToTable("categorias", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("IdCliente")
                        .HasName("cliente_id_pk");

                    b.HasIndex("IdPersona");

                    b.ToTable("cliente", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdVoucher")
                        .HasColumnType("int")
                        .HasColumnName("id_voucher");

                    b.HasKey("IdCompra")
                        .HasName("compra_id_pk");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdVoucher");

                    b.ToTable("compra", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleCompra", b =>
                {
                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_expiracion");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_compra");

                    b.HasKey("IdCompra", "IdInsumo")
                        .HasName("detalle_compra_id_pk");

                    b.HasIndex("IdInsumo");

                    b.ToTable("detalle_compra", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleDashMenu", b =>
                {
                    b.Property<int>("IdMenu")
                        .HasColumnType("int")
                        .HasColumnName("id_menu");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdMenu", "IdRol")
                        .HasName("detalle_dash_menu_id_pk");

                    b.HasIndex("IdRol");

                    b.ToTable("detalle_dash_menu", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleInventario", b =>
                {
                    b.Property<int>("IdDetInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_det_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetInventario"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    b.Property<int>("IdInventario")
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    b.Property<int>("StockTotal")
                        .HasColumnType("int")
                        .HasColumnName("stock_total");

                    b.HasKey("IdDetInventario")
                        .HasName("detalle_inventario_id_pk");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdInventario");

                    b.ToTable("detalle_inventario", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleProduccion", b =>
                {
                    b.Property<int>("IdProduccion")
                        .HasColumnType("int")
                        .HasColumnName("id_produccion");

                    b.Property<int>("IdProductoSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_sucursal");

                    b.Property<int?>("CantidadSalida")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_salida");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_salida");

                    b.HasKey("IdProduccion", "IdProductoSucursal")
                        .HasName("detalle_produccion_id_pk");

                    b.HasIndex("IdProductoSucursal");

                    b.ToTable("detalle_produccion", "Produccion");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_det_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetVenta"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProductoSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_sucursal");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetVenta")
                        .HasName("detalle_venta_id_pk");

                    b.HasIndex("IdProductoSucursal");

                    b.HasIndex("IdVenta");

                    b.ToTable("detalle_ventas", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<int>("IdComprobante")
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    b.Property<string>("NroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nro_documento");

                    b.HasKey("IdDocumento")
                        .HasName("documento_id_pk");

                    b.HasIndex("IdComprobante");

                    b.ToTable("documentos", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.HasKey("IdEmpleado")
                        .HasName("empleado_id_pk");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("empleado", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Entrada", b =>
                {
                    b.Property<int>("IdInventario")
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_Ingreso");

                    b.HasKey("IdInventario", "IdCompra")
                        .HasName("entrada_id_pk");

                    b.HasIndex("IdCompra");

                    b.ToTable("entradas", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Abreviacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("abreviacion");

                    b.Property<int?>("IdEstadoPadre")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_padre");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado")
                        .HasName("estado_id_pk");

                    b.HasIndex("IdEstadoPadre");

                    b.HasIndex(new[] { "Nombre" }, "estado_descripcion_uk")
                        .IsUnique()
                        .HasFilter("[nombre] IS NOT NULL");

                    b.ToTable("estado", "Generico");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Imagene", b =>
                {
                    b.Property<int>("IdImg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_img");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImg"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("IdImg")
                        .HasName("imagenes_id_pk");

                    b.ToTable("imagenes", "Generico");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Insumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInsumo"));

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("IdInsumo")
                        .HasName("insumo_id_pk");

                    b.HasIndex("IdUnidad");

                    b.ToTable("insumo", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.HasKey("IdInventario")
                        .HasName("inventario_id_pk");

                    b.HasIndex("IdSucursal");

                    b.ToTable("inventario", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.MenuDash", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_menu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("DataTarget")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("data_target");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("IdMenu")
                        .HasName("dashboard_id_pk");

                    b.ToTable("menu_dash", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMesa")
                        .HasName("mesa_id_pk");

                    b.ToTable("mesas", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdMetodo")
                        .HasName("metodo_pago_id_pk");

                    b.ToTable("metodo_pago", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("genero");

                    b.Property<string>("NroDocumento")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("nro_Documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoPersona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_persona");

                    b.HasKey("IdPersona")
                        .HasName("persona_id_pk");

                    b.HasIndex(new[] { "Email" }, "personas_email_uk")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "NroDocumento" }, "personas_numero_documento_uk")
                        .IsUnique()
                        .HasFilter("[nro_Documento] IS NOT NULL");

                    b.HasIndex(new[] { "Telefono" }, "personas_phone_uk")
                        .IsUnique()
                        .HasFilter("[telefono] IS NOT NULL");

                    b.ToTable("personas", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.PersonaJuridica", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("razon_social");

                    b.HasKey("IdPersona")
                        .HasName("persona_juridica_id_pk");

                    b.ToTable("persona_juridicas", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.PersonaNatural", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("segundo_nombre");

                    b.HasKey("IdPersona")
                        .HasName("persona_natural_id_pk");

                    b.ToTable("persona_natural", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Produccion", b =>
                {
                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduccion"));

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_total");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdProduccion")
                        .HasName("produccion_id_pk");

                    b.ToTable("produccion", "Produccion");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Derivar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("derivar");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdImg")
                        .HasColumnType("int")
                        .HasColumnName("id_img");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProducto")
                        .HasName("producto_id_pk");

                    b.HasIndex("IdImg");

                    b.ToTable("productos", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.ProductoSucursal", b =>
                {
                    b.Property<int>("IdProductoSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto_sucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoSucursal"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProductoSucursal")
                        .HasName("producto_local_id_pk");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdUnidad");

                    b.ToTable("producto_sucursal", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Vende")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vende");

                    b.HasKey("IdProveedor")
                        .HasName("proveedor_id_pk");

                    b.HasIndex("IdPersona");

                    b.ToTable("proveedor", "Almacen");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Abreviacion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("abreviacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("roles_id_pk");

                    b.HasIndex("IdEstado");

                    b.ToTable("roles", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Salida", b =>
                {
                    b.Property<int>("IdDetInventario")
                        .HasColumnType("int")
                        .HasColumnName("id_det_inventario");

                    b.Property<int>("IdProduccion")
                        .HasColumnType("int")
                        .HasColumnName("id_produccion");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.HasKey("IdDetInventario", "IdProduccion", "IdSucursal")
                        .HasName("salida_id_pk");

                    b.HasIndex("IdProduccion");

                    b.HasIndex("IdSucursal");

                    b.ToTable("salidas", "Produccion");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<int>("IdAmbiente")
                        .HasColumnType("int")
                        .HasColumnName("id_ambiente");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdUbigeo")
                        .HasColumnType("int")
                        .HasColumnName("id_ubigeo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdSucursal")
                        .HasName("sucursal_id_pk");

                    b.HasIndex("IdAmbiente");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdUbigeo");

                    b.ToTable("sucursal", "Generico");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.SucursalUsuario", b =>
                {
                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdSucursal", "IdUsuario")
                        .HasName("sucursal_id_usuario_pk");

                    b.HasIndex("IdUsuario");

                    b.ToTable("sucursal_usuario", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoComprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprobante"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdComprobante")
                        .HasName("tipo_comprobante_id_pk");

                    b.ToTable("tipo_comprobantes", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoPedido", b =>
                {
                    b.Property<int>("IdTipoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPedido"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoPedido")
                        .HasName("tipo_pedido_id_pk");

                    b.ToTable("tipo_pedido", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoTransaccion", b =>
                {
                    b.Property<int>("IdTipoTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transaccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTransaccion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoTransaccion")
                        .HasName("tipo_transaccion_id_pk");

                    b.ToTable("tipo_transaccion", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Ubigeo", b =>
                {
                    b.Property<int>("IdUbigeo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubigeo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbigeo"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("codigo");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provincia");

                    b.HasKey("IdUbigeo")
                        .HasName("ubigeo_id_pk");

                    b.ToTable("ubigeo", "Generico");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.UnidadMedicion", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Abreviacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("abreviacion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdUnidad")
                        .HasName("unidad_medicion_id_pk");

                    b.ToTable("unidad_medicion", "Generico");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CambiarPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cambiar_password");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdImg")
                        .HasColumnType("int")
                        .HasColumnName("id_img");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_id_pk");

                    b.HasIndex("IdImg");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "usuario_user_email_uk")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "UserName" }, "usuario_user_name_uk")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("usuario", "Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<decimal?>("CostoBase")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo_base");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdApertura")
                        .HasColumnType("int")
                        .HasColumnName("id_apertura");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdComprobante")
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdMetodo")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int>("IdTipoPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_pedido");

                    b.Property<int>("IdVoucher")
                        .HasColumnType("int")
                        .HasColumnName("id_voucher");

                    b.Property<decimal?>("Igv")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("igv");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("NroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nro_documento");

                    b.Property<string>("NroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nro_serie");

                    b.Property<string>("Observacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("observacion");

                    b.Property<decimal?>("Vuelto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("vuelto");

                    b.HasKey("IdVenta")
                        .HasName("venta_id_pk");

                    b.HasIndex("IdApertura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMetodo");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoPedido");

                    b.HasIndex("IdVoucher");

                    b.HasIndex(new[] { "NroDocumento" }, "ventas_numero_documento_uk")
                        .IsUnique()
                        .HasFilter("[nro_documento] IS NOT NULL");

                    b.HasIndex(new[] { "NroSerie" }, "ventas_numero_serie_uk")
                        .IsUnique()
                        .HasFilter("[nro_serie] IS NOT NULL");

                    b.ToTable("ventas", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Voucher", b =>
                {
                    b.Property<int>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_voucher");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVoucher"));

                    b.Property<string>("Cantidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cantidad");

                    b.Property<string>("FechaEmision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoTransaccion")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transaccion");

                    b.Property<string>("Igv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("igv");

                    b.Property<string>("ImporteTotal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("importe_total");

                    b.Property<string>("PrecioUnitario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdVoucher")
                        .HasName("voucher_id_pk");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoTransaccion");

                    b.ToTable("voucher", "Ventas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Ambiente", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Mesa", "IdMesaNavigation")
                        .WithMany("Ambientes")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("mesa_id_fk");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.AperturaCaja", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Caja", "IdCajaNavigation")
                        .WithMany("AperturaCajas")
                        .HasForeignKey("IdCaja")
                        .IsRequired()
                        .HasConstraintName("caja_id_fk");

                    b.Navigation("IdCajaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Categoria", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Categoria", "IdCategoriaPadreNavigation")
                        .WithMany("InverseIdCategoriaPadreNavigation")
                        .HasForeignKey("IdCategoriaPadre")
                        .HasConstraintName("categorias_padre_fk");

                    b.Navigation("IdCategoriaPadreNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Cliente", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("persona_id_fk");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Compra", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Proveedor", "IdProveedorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("provedor_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Voucher", "IdVoucherNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdVoucher")
                        .IsRequired()
                        .HasConstraintName("voucher_id_fk");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdVoucherNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleCompra", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Compra", "IdCompraNavigation")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdCompra")
                        .IsRequired()
                        .HasConstraintName("compra_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Insumo", "IdInsumoNavigation")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdInsumo")
                        .IsRequired()
                        .HasConstraintName("insumo_id_fk");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdInsumoNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleDashMenu", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.MenuDash", "IdMenuNavigation")
                        .WithMany("DetalleDashMenus")
                        .HasForeignKey("IdMenu")
                        .IsRequired()
                        .HasConstraintName("menu_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Role", "IdRolNavigation")
                        .WithMany("DetalleDashMenus")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("rol_id_fk");

                    b.Navigation("IdMenuNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleInventario", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Estado", "IdEstadoNavigation")
                        .WithMany("DetalleInventarios")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("estado_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Insumo", "IdInsumoNavigation")
                        .WithMany("DetalleInventarios")
                        .HasForeignKey("IdInsumo")
                        .IsRequired()
                        .HasConstraintName("det_insumo_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Inventario", "IdInventarioNavigation")
                        .WithMany("DetalleInventarios")
                        .HasForeignKey("IdInventario")
                        .IsRequired()
                        .HasConstraintName("inventario_id_fk");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdInsumoNavigation");

                    b.Navigation("IdInventarioNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleProduccion", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Produccion", "IdProduccionNavigation")
                        .WithMany("DetalleProduccions")
                        .HasForeignKey("IdProduccion")
                        .IsRequired()
                        .HasConstraintName("produccion_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.ProductoSucursal", "IdProductoSucursalNavigation")
                        .WithMany("DetalleProduccions")
                        .HasForeignKey("IdProductoSucursal")
                        .IsRequired()
                        .HasConstraintName("sucurusal_id_fk");

                    b.Navigation("IdProduccionNavigation");

                    b.Navigation("IdProductoSucursalNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleVenta", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.ProductoSucursal", "IdProductoSucursalNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdProductoSucursal")
                        .IsRequired()
                        .HasConstraintName("producto_sucursal_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("venta_id_fk");

                    b.Navigation("IdProductoSucursalNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Documento", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.TipoComprobante", "IdComprobanteNavigation")
                        .WithMany("Documentos")
                        .HasForeignKey("IdComprobante")
                        .IsRequired()
                        .HasConstraintName("comprobante_tipo_id_fk");

                    b.Navigation("IdComprobanteNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Empleado", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("empleado_persona_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Role", "IdRolNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("rol_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursal_id_fk");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Entrada", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Compra", "IdCompraNavigation")
                        .WithMany("Entrada")
                        .HasForeignKey("IdCompra")
                        .IsRequired()
                        .HasConstraintName("compras_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Inventario", "IdInventarioNavigation")
                        .WithMany("Entrada")
                        .HasForeignKey("IdInventario")
                        .IsRequired()
                        .HasConstraintName("inventario_id_entrada_fk");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdInventarioNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Estado", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Estado", "IdEstadoPadreNavigation")
                        .WithMany("InverseIdEstadoPadreNavigation")
                        .HasForeignKey("IdEstadoPadre")
                        .HasConstraintName("estado_padre_fk");

                    b.Navigation("IdEstadoPadreNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Insumo", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.UnidadMedicion", "IdUnidadNavigation")
                        .WithMany("Insumos")
                        .HasForeignKey("IdUnidad")
                        .IsRequired()
                        .HasConstraintName("unidad_medida_id_fk");

                    b.Navigation("IdUnidadNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Inventario", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursal_id_fk");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.PersonaJuridica", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithOne("PersonaJuridica")
                        .HasForeignKey("DBSenorialModels.Senorial.PersonaJuridica", "IdPersona")
                        .IsRequired()
                        .HasConstraintName("persona_id_fk");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.PersonaNatural", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithOne("PersonaNatural")
                        .HasForeignKey("DBSenorialModels.Senorial.PersonaNatural", "IdPersona")
                        .IsRequired()
                        .HasConstraintName("personas_id_fk");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Producto", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Imagene", "IdImgNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdImg")
                        .IsRequired()
                        .HasConstraintName("img_id_fk");

                    b.Navigation("IdImgNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.ProductoSucursal", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Categoria", "IdCategoriaNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("categorias_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Producto", "IdProductoNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("producto_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursales_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.UnidadMedicion", "IdUnidadNavigation")
                        .WithMany("ProductoSucursals")
                        .HasForeignKey("IdUnidad")
                        .IsRequired()
                        .HasConstraintName("unidad_medida_id_fk");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdUnidadNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Proveedor", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithMany("Proveedors")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_fk");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Role", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Estado", "IdEstadoNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("estado_id_fk");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Salida", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.DetalleInventario", "IdDetInventarioNavigation")
                        .WithMany("Salida")
                        .HasForeignKey("IdDetInventario")
                        .IsRequired()
                        .HasConstraintName("det_inventario_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Produccion", "IdProduccionNavigation")
                        .WithMany("Salida")
                        .HasForeignKey("IdProduccion")
                        .IsRequired()
                        .HasConstraintName("produccion_salida_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("Salida")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursal_id_fk");

                    b.Navigation("IdDetInventarioNavigation");

                    b.Navigation("IdProduccionNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Sucursal", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Ambiente", "IdAmbienteNavigation")
                        .WithMany("Sucursals")
                        .HasForeignKey("IdAmbiente")
                        .IsRequired()
                        .HasConstraintName("ambientes_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Documento", "IdDocumentoNavigation")
                        .WithMany("Sucursals")
                        .HasForeignKey("IdDocumento")
                        .IsRequired()
                        .HasConstraintName("documento_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Ubigeo", "IdUbigeoNavigation")
                        .WithMany("Sucursals")
                        .HasForeignKey("IdUbigeo")
                        .IsRequired()
                        .HasConstraintName("ubigeo_id_fk");

                    b.Navigation("IdAmbienteNavigation");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdUbigeoNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.SucursalUsuario", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("SucursalUsuarios")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursal_user_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Usuario", "IdUsuarioNavigation")
                        .WithMany("SucursalUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("usuario_id_fk");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Usuario", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Imagene", "IdImgNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdImg")
                        .IsRequired()
                        .HasConstraintName("img_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Persona", "IdPersonaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("personas_usuario_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("roles_id_fk");

                    b.Navigation("IdImgNavigation");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Venta", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.AperturaCaja", "IdAperturaNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdApertura")
                        .IsRequired()
                        .HasConstraintName("apertura_caja_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("cliente_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.TipoComprobante", "IdComprobanteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdComprobante")
                        .IsRequired()
                        .HasConstraintName("comprobante_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("empleado_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Estado", "IdEstadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("estado_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.MetodoPago", "IdMetodoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdMetodo")
                        .IsRequired()
                        .HasConstraintName("metodo_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Sucursal", "IdSucursalNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("sucursales_ventas_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.TipoPedido", "IdTipoPedidoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdTipoPedido")
                        .IsRequired()
                        .HasConstraintName("tipo_pedido_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.Voucher", "IdVoucherNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdVoucher")
                        .IsRequired()
                        .HasConstraintName("voucher_id_fk");

                    b.Navigation("IdAperturaNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdComprobanteNavigation");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdMetodoNavigation");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdTipoPedidoNavigation");

                    b.Navigation("IdVoucherNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Voucher", b =>
                {
                    b.HasOne("DBSenorialModels.Senorial.Estado", "IdEstadoNavigation")
                        .WithMany("Vouchers")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("estados_id_fk");

                    b.HasOne("DBSenorialModels.Senorial.TipoTransaccion", "IdTipoTransaccionNavigation")
                        .WithMany("Vouchers")
                        .HasForeignKey("IdTipoTransaccion")
                        .IsRequired()
                        .HasConstraintName("tipo_transaccion_id_fk");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdTipoTransaccionNavigation");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Ambiente", b =>
                {
                    b.Navigation("Sucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.AperturaCaja", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Caja", b =>
                {
                    b.Navigation("AperturaCajas");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Categoria", b =>
                {
                    b.Navigation("InverseIdCategoriaPadreNavigation");

                    b.Navigation("ProductoSucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Compra", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.DetalleInventario", b =>
                {
                    b.Navigation("Salida");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Documento", b =>
                {
                    b.Navigation("Sucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Empleado", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Estado", b =>
                {
                    b.Navigation("DetalleInventarios");

                    b.Navigation("InverseIdEstadoPadreNavigation");

                    b.Navigation("Roles");

                    b.Navigation("Venta");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Imagene", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Insumo", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("DetalleInventarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Inventario", b =>
                {
                    b.Navigation("DetalleInventarios");

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.MenuDash", b =>
                {
                    b.Navigation("DetalleDashMenus");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Mesa", b =>
                {
                    b.Navigation("Ambientes");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.MetodoPago", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Persona", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("PersonaJuridica");

                    b.Navigation("PersonaNatural");

                    b.Navigation("Proveedors");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Produccion", b =>
                {
                    b.Navigation("DetalleProduccions");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Producto", b =>
                {
                    b.Navigation("ProductoSucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.ProductoSucursal", b =>
                {
                    b.Navigation("DetalleProduccions");

                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Role", b =>
                {
                    b.Navigation("DetalleDashMenus");

                    b.Navigation("Empleados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Sucursal", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Inventarios");

                    b.Navigation("ProductoSucursals");

                    b.Navigation("Salida");

                    b.Navigation("SucursalUsuarios");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoComprobante", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoPedido", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.TipoTransaccion", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Ubigeo", b =>
                {
                    b.Navigation("Sucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.UnidadMedicion", b =>
                {
                    b.Navigation("Insumos");

                    b.Navigation("ProductoSucursals");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Usuario", b =>
                {
                    b.Navigation("SucursalUsuarios");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("DBSenorialModels.Senorial.Voucher", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
