<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
    <ProjectReference Include="..\CommonModels\CommonModels.csproj" />
    <ProjectReference Include="..\IBusiness\IBusiness.csproj" />
    <ProjectReference Include="..\RequestResponseModels\RequestResponseModels.csproj" />
    <ProjectReference Include="..\UtilSecurity\UtilitySecurity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Schema_Almacen\Categorias\" />
    <Folder Include="Controllers\Schema_Almacen\Compra\" />
    <Folder Include="Controllers\Schema_Almacen\DetalleCompra\" />
    <Folder Include="Controllers\Schema_Almacen\DetalleInventario\" />
    <Folder Include="Controllers\Schema_Almacen\Entradas\" />
    <Folder Include="Controllers\Schema_Almacen\Insumo\" />
    <Folder Include="Controllers\Schema_Almacen\Inventario\" />
    <Folder Include="Controllers\Schema_Almacen\Proveedor\" />
    <Folder Include="Controllers\Schema_Generico\Estado\" />
    <Folder Include="Controllers\Schema_Generico\Imagenes\" />
    <Folder Include="Controllers\Schema_Generico\UnidadMedicion\" />
    <Folder Include="Controllers\Schema_Generico\Ubigeo\" />
    <Folder Include="Controllers\Schema_Generico\TipoEstado\" />
    <Folder Include="Controllers\Schema_Generico\Sucursal\" />
    <Folder Include="Controllers\Schema_Produccion\DetalleProduccion\" />
    <Folder Include="Controllers\Schema_Produccion\Salidas\" />
    <Folder Include="Controllers\Schema_Produccion\Produccion\" />
    <Folder Include="Controllers\Schema_Usuarios\DetalleDashMenu\" />
    <Folder Include="Controllers\Schema_Usuarios\MenuDash\" />
    <Folder Include="Controllers\Schema_Usuarios\Genero\" />
    <Folder Include="Controllers\Schema_Usuarios\Usuario\" />
    <Folder Include="Controllers\Schema_Usuarios\TipoDocumento\" />
    <Folder Include="Controllers\Schema_Usuarios\Roles\" />
    <Folder Include="Controllers\Schema_Usuarios\PersonaNatural\" />
    <Folder Include="Controllers\Schema_Usuarios\PersonaJuridica\" />
    <Folder Include="Controllers\Schema_Usuarios\Persona\" />
    <Folder Include="Controllers\Schema_Ventas\Ambiente\" />
    <Folder Include="Controllers\Schema_Ventas\Cliente\" />
    <Folder Include="Controllers\Schema_Ventas\DetalleVentas\" />
    <Folder Include="Controllers\Schema_Ventas\Documentos\" />
    <Folder Include="Controllers\Schema_Ventas\Empleados\" />
    <Folder Include="Controllers\Schema_Ventas\Mesas\" />
    <Folder Include="Controllers\Schema_Ventas\MetodoPago\" />
    <Folder Include="Controllers\Schema_Ventas\AperturaCaja\" />
    <Folder Include="Controllers\Schema_Ventas\Cajas\" />
    <Folder Include="Controllers\Schema_Ventas\Voucher\" />
    <Folder Include="Controllers\Schema_Ventas\Ventas\" />
    <Folder Include="Controllers\Schema_Ventas\TipoTransaccion\" />
    <Folder Include="Controllers\Schema_Ventas\TipoPedido\" />
    <Folder Include="Controllers\Schema_Ventas\TipoComprobante\" />
    <Folder Include="Controllers\Schema_Ventas\SucursalUsuario\" />
    <Folder Include="Controllers\Schema_Ventas\ProductoSucursal\" />
    <Folder Include="Controllers\Schema_Ventas\Productos\" />
  </ItemGroup>

</Project>
