<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonModels\CommonModels.csproj" />
    <ProjectReference Include="..\DBSenorialModels\DBSenorialModels.csproj" />
    <ProjectReference Include="..\ExcelGenerator\ExcelGenerator.csproj" />
    <ProjectReference Include="..\IBusiness\IBusiness.csproj" />
    <ProjectReference Include="..\IRepository\IRepository.csproj" />
    <ProjectReference Include="..\IServices\IServices.csproj" />
    <ProjectReference Include="..\PdfGenerator\PdfGenerator.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\RequestResponseModels\RequestResponseModels.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
    <ProjectReference Include="..\UtilConstants\UtilityConstants.csproj" />
    <ProjectReference Include="..\UtilityAutoMapper\UtilityAutoMapper.csproj" />
    <ProjectReference Include="..\UtilSecurity\UtilitySecurity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Schema_Almacen\Categorias\" />
    <Folder Include="Schema_Almacen\Compra\" />
    <Folder Include="Schema_Almacen\DetalleCompra\" />
    <Folder Include="Schema_Almacen\DetalleInventario\" />
    <Folder Include="Schema_Almacen\Entradas\" />
    <Folder Include="Schema_Almacen\Insumo\" />
    <Folder Include="Schema_Almacen\Inventario\" />
    <Folder Include="Schema_Almacen\Proveedor\" />
    <Folder Include="Schema_Generico\Estado\" />
    <Folder Include="Schema_Generico\Imagenes\" />
    <Folder Include="Schema_Generico\UnidadMedicion\" />
    <Folder Include="Schema_Generico\Ubigeo\" />
    <Folder Include="Schema_Generico\TipoEstado\" />
    <Folder Include="Schema_Generico\Sucursal\" />
    <Folder Include="Schema_Produccion\DetalleProduccion\" />
    <Folder Include="Schema_Produccion\Salidas\" />
    <Folder Include="Schema_Produccion\Produccion\" />
    <Folder Include="Schema_Usuarios\DetalleDashMenu\" />
    <Folder Include="Schema_Usuarios\Genero\" />
    <Folder Include="Schema_Usuarios\MenuDash\" />
    <Folder Include="Schema_Usuarios\Usuario\" />
    <Folder Include="Schema_Usuarios\TipoDocumento\" />
    <Folder Include="Schema_Usuarios\Roles\" />
    <Folder Include="Schema_Usuarios\PersonaNatural\" />
    <Folder Include="Schema_Usuarios\PersonaJuridica\" />
    <Folder Include="Schema_Usuarios\Persona\" />
    <Folder Include="Schema_Ventas\Ambiente\" />
    <Folder Include="Schema_Ventas\Cliente\" />
    <Folder Include="Schema_Ventas\DetalleVentas\" />
    <Folder Include="Schema_Ventas\Documentos\" />
    <Folder Include="Schema_Ventas\Empleados\" />
    <Folder Include="Schema_Ventas\Mesas\" />
    <Folder Include="Schema_Ventas\MetodoPago\" />
    <Folder Include="Schema_Ventas\AperturaCajas\" />
    <Folder Include="Schema_Ventas\Cajas\" />
    <Folder Include="Schema_Ventas\Voucher\" />
    <Folder Include="Schema_Ventas\Ventas\" />
    <Folder Include="Schema_Ventas\TipoTransaccion\" />
    <Folder Include="Schema_Ventas\TipoPedido\" />
    <Folder Include="Schema_Ventas\TipoComprobante\" />
    <Folder Include="Schema_Ventas\SucursalUsuario\" />
    <Folder Include="Schema_Ventas\ProductoSucursal\" />
    <Folder Include="Schema_Ventas\Productos\" />
  </ItemGroup>

</Project>
