<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Request\Schema_Almacen\Categorias\" />
    <Folder Include="Request\Schema_Almacen\Compra\" />
    <Folder Include="Request\Schema_Almacen\DetalleCompra\" />
    <Folder Include="Request\Schema_Almacen\DetalleInventario\" />
    <Folder Include="Request\Schema_Almacen\Insumo\" />
    <Folder Include="Request\Schema_Almacen\Entradas\" />
    <Folder Include="Request\Schema_Almacen\Inventario\" />
    <Folder Include="Request\Schema_Almacen\SubCategoria\" />
    <Folder Include="Request\Schema_Almacen\Proveedor\" />
    <Folder Include="Request\Schema_Generico\Estado\" />
    <Folder Include="Request\Schema_Generico\Imagenes\" />
    <Folder Include="Request\Schema_Generico\UnidadMedicion\" />
    <Folder Include="Request\Schema_Generico\Ubigeo\" />
    <Folder Include="Request\Schema_Generico\TipoEstado\" />
    <Folder Include="Request\Schema_Generico\Sucursal\" />
    <Folder Include="Request\Schema_Produccion\DetalleProduccion\" />
    <Folder Include="Request\Schema_Produccion\Salidas\" />
    <Folder Include="Request\Schema_Produccion\Produccion\" />
    <Folder Include="Request\Schema_Usuarios\DetalleDashMenu\" />
    <Folder Include="Request\Schema_Usuarios\Error\" />
    <Folder Include="Request\Schema_Usuarios\MenuDash\" />
    <Folder Include="Request\Schema_Usuarios\Genero\" />
    <Folder Include="Request\Schema_Usuarios\Usuario\" />
    <Folder Include="Request\Schema_Usuarios\TipoDocumento\" />
    <Folder Include="Request\Schema_Usuarios\Roles\" />
    <Folder Include="Request\Schema_Usuarios\PersonaNatural\" />
    <Folder Include="Request\Schema_Usuarios\PersonaJuridica\" />
    <Folder Include="Request\Schema_Usuarios\Persona\" />
    <Folder Include="Request\Schema_Ventas\Ambiente\" />
    <Folder Include="Request\Schema_Ventas\Cliente\" />
    <Folder Include="Request\Schema_Ventas\DetalleMesa\" />
    <Folder Include="Request\Schema_Ventas\DetalleVentas\" />
    <Folder Include="Request\Schema_Ventas\Documentos\" />
    <Folder Include="Request\Schema_Ventas\Empleados\" />
    <Folder Include="Request\Schema_Ventas\Mesas\" />
    <Folder Include="Request\Schema_Ventas\MetodoPago\" />
    <Folder Include="Request\Schema_Ventas\Voucher\" />
    <Folder Include="Request\Schema_Ventas\Ventas\" />
    <Folder Include="Request\Schema_Ventas\TipoTransaccion\" />
    <Folder Include="Request\Schema_Ventas\TipoPedido\" />
    <Folder Include="Request\Schema_Ventas\TipoComprobante\" />
    <Folder Include="Request\Schema_Ventas\SucursalUsuario\" />
    <Folder Include="Request\Schema_Ventas\Productos\" />
    <Folder Include="Request\Schema_Ventas\ProductoSucursal\" />
    <Folder Include="Response\Schema_Almacen\Categorias\" />
    <Folder Include="Response\Schema_Almacen\Compra\" />
    <Folder Include="Response\Schema_Almacen\DetalleCompra\" />
    <Folder Include="Response\Schema_Almacen\DetalleInventario\" />
    <Folder Include="Response\Schema_Almacen\Entradas\" />
    <Folder Include="Response\Schema_Almacen\Insumo\" />
    <Folder Include="Response\Schema_Almacen\Inventario\" />
    <Folder Include="Response\Schema_Almacen\SubCategoria\" />
    <Folder Include="Response\Schema_Almacen\Proveedor\" />
    <Folder Include="Response\Schema_Generico\Estado\" />
    <Folder Include="Response\Schema_Generico\Imagenes\" />
    <Folder Include="Response\Schema_Generico\UnidadMedicion\" />
    <Folder Include="Response\Schema_Generico\Ubigeo\" />
    <Folder Include="Response\Schema_Generico\TipoEstado\" />
    <Folder Include="Response\Schema_Generico\Sucursal\" />
    <Folder Include="Response\Schema_Produccion\DetalleProduccion\" />
    <Folder Include="Response\Schema_Produccion\Salidas\" />
    <Folder Include="Response\Schema_Produccion\Produccion\" />
    <Folder Include="Response\Schema_Usuarios\DetalleDashMenu\" />
    <Folder Include="Response\Schema_Usuarios\Error\" />
    <Folder Include="Response\Schema_Usuarios\Genero\" />
    <Folder Include="Response\Schema_Usuarios\MenuDash\" />
    <Folder Include="Response\Schema_Usuarios\Usuario\" />
    <Folder Include="Response\Schema_Usuarios\TipoDocumento\" />
    <Folder Include="Response\Schema_Usuarios\Roles\" />
    <Folder Include="Response\Schema_Usuarios\Persona\" />
    <Folder Include="Response\Schema_Usuarios\PersonaNatural\" />
    <Folder Include="Response\Schema_Usuarios\PersonaJuridica\" />
    <Folder Include="Response\Schema_Ventas\Ambiente\" />
    <Folder Include="Response\Schema_Ventas\Cliente\" />
    <Folder Include="Response\Schema_Ventas\DetalleMesa\" />
    <Folder Include="Response\Schema_Ventas\DetalleVentas\" />
    <Folder Include="Response\Schema_Ventas\Documentos\" />
    <Folder Include="Response\Schema_Ventas\Empleados\" />
    <Folder Include="Response\Schema_Ventas\Mesas\" />
    <Folder Include="Response\Schema_Ventas\MetodoPago\" />
    <Folder Include="Response\Schema_Ventas\SucursalUsuario\" />
    <Folder Include="Response\Schema_Ventas\Voucher\" />
    <Folder Include="Response\Schema_Ventas\Ventas\" />
    <Folder Include="Response\Schema_Ventas\TipoTransaccion\" />
    <Folder Include="Response\Schema_Ventas\TipoPedido\" />
    <Folder Include="Response\Schema_Ventas\TipoComprobante\" />
    <Folder Include="Response\Schema_Ventas\ProductoSucursal\" />
    <Folder Include="Response\Schema_Ventas\Productos\" />
  </ItemGroup>

</Project>
