name: m_senorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0' # Asegúrate de que esta versión sea compatible con todas las dependencias

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.2.1
  dio: ^5.4.1
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/imagenes/
