<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SMS\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonModels\CommonModels.csproj" />
    <ProjectReference Include="..\DBSenorialModels\DBSenorialModels.csproj" />
    <ProjectReference Include="..\IServices\IServices.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\RequestResponseModels\RequestResponseModels.csproj" />
  </ItemGroup>

</Project>
